---
- name: Add EPEL repository.
  yum:
    name: "{{ epel_repo_url }}"
    state: present

- name: Add MySQL repository.
  yum:
    name: "{{ mysql_repo_url }}"
    state: present

- name: enable MySQL 5.7 repository.
  ini_file:
    path: /etc/yum.repos.d/mysql-community.repo
    section: mysql57-community
    option: enabled
    value: 1
    backup: yes

- name: disable MySQL 5.6 repository.
  ini_file:
    path: /etc/yum.repos.d/mysql-community.repo
    section: mysql56-community
    option: enabled
    value: 0
    backup: yes

- name: Install zip
  yum:
    name: zip

- name: Install unzip
  yum:
    name: unzip

- name: Install p7zip
  yum:
    name: p7zip

- name: Install Java 1.8.0 OpenJDK Headless
  yum:
    name: java-1.8.0-openjdk-headless.x86_64

- name: SET SELinux targeted permissive.
  selinux:
    policy: targeted
    state: permissive

- name: SLM Installer.
  command: /bin/bash {{ slm_path }} {{ slm_installer_option }} -p {{ slm_admin_passwd }}
